name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, 1.59]

    steps:
    - uses: actions/checkout@v4

    - name: Install ${{ matrix.rust }}
      run: rustup install ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

    - name: Downgrade dependencies for MSRV
      if: ${{ matrix.rust == '1.59' }}
      run: |
        cargo update -p byteorder --precise 1.4.3
        cargo update -p jobserver --precise 0.1.26
        cargo update -p base64ct --precise 1.5.3

    - run: cargo check --all --bins --examples
    - run: cargo test --all

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cargo clippy --all-targets --all-features

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: cargo fmt --all -- --check
    - run: cargo doc

  fuzz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup install nightly --profile minimal && rustup default nightly
      - run: cargo install cargo-fuzz

      - name: compile fuzz
        run: |
          cargo fuzz build fuzz_read
